apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager:
        install: false
      global:
        hosts:
          domain: apps-crc.testing
          hostSuffix: null
        ingress:
          configureCertmanager: false
          tls:
            secretName: null
    version: 6.8.1
