apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amqstreams-int
  namespace: openshift-gitops
spec:
  destination:
    namespace: <namespace>
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: gitops/opsteam/int
    repoURL: https://github.com/mthirion/rhaf-demo.git
    targetRevision: HEAD
  syncPolicy: {}
